# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Create Release - Node.js

on:
  push:
    # branches:
    #   - "build/nginx-production"
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3

    - uses: pnpm/action-setup@v2
      with:
        version: 8

    - name: Install dependences Svelte - Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'

    - name: Install dependencies
      run: pnpm install --frozen-lockfile

    - name: Build Svelte - Node.js ${{ matrix.node-version }}
      run: pnpm run build

    - name: Zip dist folder
      uses: montudor/action-zip@v1
      with:
        args: zip -qq -r MutinyNginxBuild.zip build

    - name: Create Release - Node.js ${{ matrix.node-version }}
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: MutinyNginxBuild.zip
        release_name: Release ${{ github.action_ref }}
        body: |
            Description of release
